name: Flask CI/CD Pipeline (DISABLED - Use ci-cd-v2.yml)

on:
  # Temporarily disabled to test new workflow
  # push:
  #   branches: [ main, staging, develop ]
  # pull_request:
  #   branches: [ main, staging ]
  # release:
  #   types: [ published ]
  workflow_dispatch:  # Manual trigger only

# Add permissions for security scanning
permissions:
  contents: read
  security-events: write
  actions: read

env:
  PYTHON_VERSION: '3.9'
  FLASK_ENV: testing

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort bandit safety
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
      continue-on-error: true
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .
      continue-on-error: true
    
    - name: Security scan with bandit
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . || true
      continue-on-error: true
    
    - name: Check for security vulnerabilities
      run: |
        safety check || true
      continue-on-error: true
    
    - name: Run tests with pytest
      run: |
        export FLASK_ENV=testing
        export SECRET_KEY=test-secret-key-for-github-actions
        pytest test_app.py -v --tb=short --cov=app --cov-report=xml --cov-report=html
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application startup
      run: |
        export FLASK_ENV=testing
        export SECRET_KEY=test-secret-key
        export PORT=5000
        
        # Start application in background
        python app.py &
        APP_PID=$!
        
        # Wait for application to start
        sleep 5
        
        # Test health endpoint
        curl -f http://localhost:5000/health
        
        # Test main endpoints
        curl -f http://localhost:5000/
        curl -f http://localhost:5000/api/status
        curl -f http://localhost:5000/api/info
        
        # Stop application
        kill $APP_PID
    
    - name: Create deployment artifact
      run: |
        tar -czf flask-app-${{ github.sha }}.tar.gz \
          app.py \
          config.py \
          requirements.txt \
          pytest.ini
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: flask-app-${{ github.sha }}
        path: flask-app-${{ github.sha }}.tar.gz
        retention-days: 30

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: flask-app-${{ github.sha }}
    
    - name: Extract artifact
      run: |
        tar -xzf flask-app-${{ github.sha }}.tar.gz
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        echo "Staging URL: https://staging.example.com"
        
        # In a real scenario, you would deploy to your staging server
        # Example deployment commands:
        # - Deploy to cloud platforms (AWS, GCP, Azure)
        # - Deploy to container orchestration (Kubernetes, Docker Swarm)
        # - Deploy to PaaS (Heroku, Railway, etc.)
        
        # Simulate deployment
        echo "Application deployed successfully to staging"
        echo "STAGING_URL=https://staging.example.com" >> $GITHUB_ENV
    
    - name: Run smoke tests on staging
      run: |
        echo "Running smoke tests on staging..."
        
        # In real scenario, test the deployed application
        # curl -f $STAGING_URL/health
        # curl -f $STAGING_URL/api/status
        
        echo "Smoke tests passed"
    
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Staging deployment successful!"
        echo "URL: $STAGING_URL"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build, deploy-staging]
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: flask-app-${{ github.sha }}
    
    - name: Extract artifact
      run: |
        tar -xzf flask-app-${{ github.sha }}.tar.gz
    
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        echo "Production URL: https://production.example.com"
        
        # In a real scenario, you would deploy to your production server
        # Example deployment commands:
        # - Blue-green deployment
        # - Rolling deployment
        # - Canary deployment
        
        # Simulate production deployment
        echo "Application deployed successfully to production"
        echo "PRODUCTION_URL=https://production.example.com" >> $GITHUB_ENV
    
    - name: Run production health checks
      run: |
        echo "Running production health checks..."
        
        # In real scenario, verify production deployment
        # curl -f $PRODUCTION_URL/health
        # curl -f $PRODUCTION_URL/api/status
        
        echo "Production health checks passed"
    
    - name: Notify deployment success
      if: success()
      run: |
        echo "🚀 Production deployment successful!"
        echo "URL: $PRODUCTION_URL"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && github.event_name == 'push'
      with:
        sarif_file: 'trivy-results.sarif'
